baseURL: 'https://lamb-project.github.io/Lamb-Project-Website/'
languageCode: 'es'
title: 'LAMB - Learning Assistants Manager and Builder'
theme: 'hugo-book'

# Configuración multiidioma
defaultContentLanguage: 'es'
defaultContentLanguageInSubdir: false

languages:
  es:
    title: 'LAMB - Gestor y Constructor de Asistentes de Aprendizaje'
    weight: 1
    languageName: 'Español'
    contentDir: 'content/es'
    params:
      description: 'Plataforma web para diseñar, entrenar y publicar asistentes de aprendizaje basados en IA sin escribir código'
  
  en:
    title: 'LAMB - Learning Assistants Manager and Builder'
    weight: 2
    languageName: 'English'
    contentDir: 'content/en'
    params:
      description: 'Web platform to design, train and publish AI-based learning assistants without writing code'
  
  ca:
    title: "LAMB - Gestor i Constructor d'Assistents d'Aprenentatge"
    weight: 3
    languageName: 'Català'
    contentDir: 'content/ca'
    params:
      description: "Plataforma web per dissenyador, entrenar i publicar assistents d'aprenentatge basats en IA sense escriure codi"
  
  eu:
    title: 'LAMB - Ikaskuntza Laguntzaileen Kudeatzailea eta Eraikitzailea'
    weight: 4
    languageName: 'Euskera'
    contentDir: 'content/eu'
    params:
      description: 'IA oinarritutako ikaskuntza laguntzaileak diseinatzeko, entrenatzeko eta argitaratzeko web plataforma koderik idatzi gabe'

# Configuración del sitio
params:
  version: '1.0'
  BookRepo: 'https://github.com/Lamb-Project/Lamb-Project-Website'
  BookEditPage: true
  BookSearch: true
  BookMenuBundle: 'menu'
  
  # SEO
  images: ['images/lamb_1.png']
  
  # Favicon
  favicon: 'images/lamb_icon.png'
  
  # Navegación
  navbar_logo: true
  
  # Footer
  copyright: 'LAMB Project'
  privacy_policy: '/privacy'

# Configuración de contenido
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: 'github'
    lineNos: true

# Outputs
outputs:
  home: ['HTML', 'RSS']
  page: ['HTML']
  section: ['HTML', 'RSS']